---
--- Generated by Luanalysis
--- Created by CHEN.
--- DateTime: 2022/10/12 17:37
---

---秒杀券id
local voucherId = ARGV[1]
--用户id
local userId = ARGV[2]
--订单id
local id = ARGV[3]

--库存key
local stockKey = 'seckill:stock:' .. voucherId
--订单key
local orderKey = 'seckill:order:' .. voucherId
--预扣记录key：保存订单与 Redis 预扣之间的绑定关系，供对账任务补偿重投
local reservationKey = 'seckill:reservation:' .. voucherId .. ':' .. userId

--库存是否充足
--库存不足
local stock = redis.call('get', stockKey)
if (not stock) then
    return 3
end
if (tonumber(stock) <= 0) then
    return 1
end

--判断用户是否下单
--存在用户 禁止重复下单
if (tonumber(redis.call('sismember', orderKey, userId)) == 1) then
    return 2
end

--扣减库存
redis.call('incrby',stockKey,-1)
--下单（保存用户）
redis.call('sadd',orderKey,userId)
--记录预扣元数据。Redis Lua 保证库存、用户集合和预扣记录一起提交。
local now = redis.call('time')[1]
redis.call('hset', reservationKey,
        'orderId', id,
        'userId', userId,
        'voucherId', voucherId,
        'reservedAt', now,
        'retryCount', '0',
        'lastRetryAt', '0')
redis.call('expire', reservationKey, 604800)
--消息发送由 Java 线程投递到 RocketMQ，Lua 只负责资格校验和预扣库存
return 0
